# config/packages/api_platform.yaml
api_platform:
    title: Hello API Platform
    version: 1.0.0
    
    # Ajout des formats JSON et JSON-LD
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']

    # Formats pour la documentation
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    # Options par défaut pour les ressources API
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

    # Autres configurations d'API Platform
    keep_legacy_inflector: false
    use_symfony_listeners: true

