@startuml diagramme_classe
!theme toy

class Utilisateur {
    - id: int
    - nom: String
    - prenom: String
    - email: String
    - motDePasse: String
    - siret: String
    - entreprise: String
    - rue: String
    - ville: String
    - codePostal: String
    - pays: String
    - referenceClient: String
    - role: String <<Employe, Particulier, Professionnel>>
    - commercial: Utilisateur
    + consulterCatalogue(): void
    + seConnecter(email: String, motDePasse: String): boolean
    + sInscrire(nom: String, email: String, motDePasse: String, typeClient: String): void
    + visualiserCommandes(): List<Commande>
    + ajouterProduitAuPanier(produit: Produit, quantite: int): void
    + supprimerProduitDuPanier(produit: Produit): void
    + validerPanier(): void
    + gererClientParticulier(client: Utilisateur): void
    + appliquerReductionProfessionnelle(commande: Commande, reduction: double): void
    + gererCatalogue(): void
    + mettreAJourStock(produit: Produit, quantite: int): void
    + validerProduit(produit: Produit): void
    + desactiverProduit(produit: Produit): void
    + gererRelationFournisseur(fournisseur: Fournisseur): void
}

class Produit {
    - id: int
    - libelleCourt: String
    - libelleLong: String
    - referenceFournisseur: String
    - prixAchatHT: double
    - prixVente: double
    - stock: int
    - actif: bool
    - photo: String
}

class Categorie {
    - id: int
    - nom: String
    - sousCategories: List<Categorie>
    + ajouterSousCategorie(sousCategorie: Categorie): void
    + ajouterProduit(produit: Produit): void
}

class Fournisseur {
    - id: int
    - nomEntreprise: String
    - contact: String
    - telephone: String
    - siret: String
}

class Commande {
    - id: int
    - date: Date
    - total: double
    - statut: String
    - adresseLivraison: String
    - adresseFacturation: String
    - modeReglement: String
    - reduction: double
    - informationReglement: String
    - produits: List<Produit>
    - quantites: List<int>
    + ajouterProduit(produit: Produit, quantite: int): void
    + supprimerProduit(produit: Produit): void
    + validerCommande(): void
}

Utilisateur "1" o-- "1..*" Commande
Commande "0..*" -- "1" Utilisateur : reductionGereePar
Commande "1" o-- "0..*" Produit : contient
Produit "0..*" -- "1" Fournisseur
Produit "0..*" -- "1" Categorie
Categorie "0..*" -- "0..*" Categorie
Produit "0..*" -- "1" Utilisateur : gestionPar

@enduml