# config/routes.yaml

controllers:
    resource: '../src/Controller/'
    type: attribute

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: ['GET', 'POST']



