# services.yaml

# config/services.yaml

services:
    App\Controller\LoginController:
        autowire: true
        autoconfigure: true
        public: false # Assurez-vous que ce service n'est pas public pour des raisons de sécurité (par défaut)
    App\Controller\MainController:
        autowire: true
        autoconfigure: true
    App\Repository\ClientRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']
    App\Repository\EmployeRepository:
        arguments:
            $registry: '@doctrine'
        tags: ['doctrine.repository_service']
    App\Controller\DashboardController:
        autowire: true
        autoconfigure: true
        public: false  # Assurez-vous que ce service n'est pas public pour des raisons de sécurité



